<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby/backstage/config.proto

namespace Backstage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ChangeConfigResponse will response `status: true` while it success
 * otherwise will return error with rpc error format
 *
 * Generated from protobuf message <code>backstage.ChangeConfigResponse</code>
 */
class ChangeConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool status = 1;</code>
     */
    protected $status = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lobby\Backstage\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool status = 1;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

}

