<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby/backstage/config.proto

namespace Backstage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>backstage.ChangeConfigRequest</code>
 */
class ChangeConfigRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lobby\Backstage\Config::initOnce();
        parent::__construct($data);
    }

}

