<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby/backstage/room.proto

namespace Backstage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>backstage.RoomRequest</code>
 */
class RoomRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint32 gameId = 2;</code>
     */
    protected $gameId = 0;
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string coverImg = 4;</code>
     */
    protected $coverImg = '';
    /**
     * Generated from protobuf field <code>string videoUrl = 5;</code>
     */
    protected $videoUrl = '';
    /**
     * Generated from protobuf field <code>string desc = 6;</code>
     */
    protected $desc = '';
    /**
     * Generated from protobuf field <code>uint32 sort = 7;</code>
     */
    protected $sort = 0;
    /**
     * Generated from protobuf field <code>uint32 status = 8;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $gameId
     *     @type string $name
     *     @type string $coverImg
     *     @type string $videoUrl
     *     @type string $desc
     *     @type int $sort
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lobby\Backstage\Room::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 gameId = 2;</code>
     * @return int
     */
    public function getGameId()
    {
        return $this->gameId;
    }

    /**
     * Generated from protobuf field <code>uint32 gameId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkUint32($var);
        $this->gameId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string coverImg = 4;</code>
     * @return string
     */
    public function getCoverImg()
    {
        return $this->coverImg;
    }

    /**
     * Generated from protobuf field <code>string coverImg = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCoverImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->coverImg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videoUrl = 5;</code>
     * @return string
     */
    public function getVideoUrl()
    {
        return $this->videoUrl;
    }

    /**
     * Generated from protobuf field <code>string videoUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVideoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->videoUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string desc = 6;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>string desc = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sort = 7;</code>
     * @return int
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * Generated from protobuf field <code>uint32 sort = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkUint32($var);
        $this->sort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 8;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

}

