<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby/backstage/user.proto

namespace Backstage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * User use for both request and response
 * will response id while it success
 *
 * Generated from protobuf message <code>backstage.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * DELETED: use while admin/backstage has case to delete user permenantly
     * DISABLED: use while admin/backstage has case to disable user's activity from game
     * ENABLED:  use while admin/backstage has case to enable back user's activity in game
     *
     * Generated from protobuf field <code>.backstage.UserStatus status = 2;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $status
     *           DELETED: use while admin/backstage has case to delete user permenantly
     *           DISABLED: use while admin/backstage has case to disable user's activity from game
     *           ENABLED:  use while admin/backstage has case to enable back user's activity in game
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lobby\Backstage\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * DELETED: use while admin/backstage has case to delete user permenantly
     * DISABLED: use while admin/backstage has case to disable user's activity from game
     * ENABLED:  use while admin/backstage has case to enable back user's activity in game
     *
     * Generated from protobuf field <code>.backstage.UserStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * DELETED: use while admin/backstage has case to delete user permenantly
     * DISABLED: use while admin/backstage has case to disable user's activity from game
     * ENABLED:  use while admin/backstage has case to enable back user's activity in game
     *
     * Generated from protobuf field <code>.backstage.UserStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Backstage\UserStatus::class);
        $this->status = $var;

        return $this;
    }

}

