<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby/backstage/user.proto

namespace Backstage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * UserLoginLogRequest for request login from api
 *
 * Generated from protobuf message <code>backstage.UserLoginLogRequest</code>
 */
class UserLoginLogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uid = 1;</code>
     */
    protected $uid = '';
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string sessionId = 3;</code>
     */
    protected $sessionId = '';
    /**
     * Generated from protobuf field <code>string agent = 4;</code>
     */
    protected $agent = '';
    /**
     * Generated from protobuf field <code>int64 loginTime = 5;</code>
     */
    protected $loginTime = 0;
    /**
     * Generated from protobuf field <code>string loginIp = 6;</code>
     */
    protected $loginIp = '';
    /**
     * Generated from protobuf field <code>string loginCountry = 7;</code>
     */
    protected $loginCountry = '';
    /**
     * Generated from protobuf field <code>int64 exitTime = 8;</code>
     */
    protected $exitTime = 0;
    /**
     * Generated from protobuf field <code>bytes extra_info = 9;</code>
     */
    protected $extra_info = '';
    /**
     * Generated from protobuf field <code>uint32 status = 10;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string cliHash = 11;</code>
     */
    protected $cliHash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *     @type string $username
     *     @type string $sessionId
     *     @type string $agent
     *     @type int|string $loginTime
     *     @type string $loginIp
     *     @type string $loginCountry
     *     @type int|string $exitTime
     *     @type string $extra_info
     *     @type int $status
     *     @type string $cliHash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lobby\Backstage\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uid = 1;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>string uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sessionId = 3;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->sessionId;
    }

    /**
     * Generated from protobuf field <code>string sessionId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string agent = 4;</code>
     * @return string
     */
    public function getAgent()
    {
        return $this->agent;
    }

    /**
     * Generated from protobuf field <code>string agent = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 loginTime = 5;</code>
     * @return int|string
     */
    public function getLoginTime()
    {
        return $this->loginTime;
    }

    /**
     * Generated from protobuf field <code>int64 loginTime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLoginTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->loginTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loginIp = 6;</code>
     * @return string
     */
    public function getLoginIp()
    {
        return $this->loginIp;
    }

    /**
     * Generated from protobuf field <code>string loginIp = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginIp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loginCountry = 7;</code>
     * @return string
     */
    public function getLoginCountry()
    {
        return $this->loginCountry;
    }

    /**
     * Generated from protobuf field <code>string loginCountry = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginCountry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 exitTime = 8;</code>
     * @return int|string
     */
    public function getExitTime()
    {
        return $this->exitTime;
    }

    /**
     * Generated from protobuf field <code>int64 exitTime = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExitTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->exitTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes extra_info = 9;</code>
     * @return string
     */
    public function getExtraInfo()
    {
        return $this->extra_info;
    }

    /**
     * Generated from protobuf field <code>bytes extra_info = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setExtraInfo($var)
    {
        GPBUtil::checkString($var, False);
        $this->extra_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 10;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cliHash = 11;</code>
     * @return string
     */
    public function getCliHash()
    {
        return $this->cliHash;
    }

    /**
     * Generated from protobuf field <code>string cliHash = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCliHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->cliHash = $var;

        return $this;
    }

}

