<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby/backstage/user.proto

namespace Backstage;

use UnexpectedValueException;

/**
 * Protobuf type <code>backstage.UserStatus</code>
 */
class UserStatus
{
    /**
     * Generated from protobuf enum <code>DELETED = 0;</code>
     */
    const DELETED = 0;
    /**
     * Generated from protobuf enum <code>DISABLED = 1;</code>
     */
    const DISABLED = 1;
    /**
     * Generated from protobuf enum <code>ENABLED = 2;</code>
     */
    const ENABLED = 2;

    private static $valueToName = [
        self::DELETED => 'DELETED',
        self::DISABLED => 'DISABLED',
        self::ENABLED => 'ENABLED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

